Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
Traceback (most recent call last):
  File "/Users/ionbota/PycharmProjects/Learn_Python/lessons_python/debugging/assert_statement.py", line 27, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
